version: '3.5'
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    env_file: ../environments/postgres-docker.env
  django:
    build:
      context: ./Dockerfile
      dockerfile: django
    env_file: ../environments/django-docker.env
    volumes:
      - ./:/home/
    working_dir: /home
    ports:
      - "8000:8000"
volumes:
  postgres-dev-data:
networks:
  default:
    external:
      name: opflow-network