name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  BRANCH: ${{github.head_ref}}
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  POSTGRES_DB: ${{secrets.POSTGRES_DB}}
  POSTGRES_USER: ${{secrets.POSTGRES_USER}}
  POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
  POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
  POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
  POSTGRES_INITDB_ARGS: ${{secrets.POSTGRES_INITDB_ARGS}}
jobs:
  build:
    runs-on: ubuntu:20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test --keepdb
